### ISSUE TITLE
Why not add year filtering to the query itself

### ISSUE THREAD

**Issue by kir-malishev** [ferru97/PyPaperBot#18]
The script now searches for all articles regardless of the year, and then filters them if the `--min-year` option is specified. Because of this, much fewer articles are downloaded from one page than they actually are. To get around this, I use a trick like this:

`python -m PyPaperBot --query="stereoscopic&as_ylo=2010" --scholar-pages=10 --dwn-dir="./"`

It would be cool to set the `as_ylo` option inside the script itself

**Comment by ferru97** [comment]
Grest suggestion!
I will implement the logic of --min-year using as_ylo as you suggest

**Comment by ferru97** [comment]
Solved

**Comment by ferru97** [comment]
Solved
