### ISSUE TITLE
Duplicate page after changing IP

### ISSUE THREAD

**Issue by kir-malishev** [ferru97/PyPaperBot#22]
Hello!

Is there any reason for this line to existing? Because of it, after changing the IP, the previous page is downloaded again.

https://github.com/ferru97/PyPaperBot/blob/a380ee00d67de88f189ccfe29da2ab30fc66c264/PyPaperBot/Scholar.py#L33

**Comment by ferru97** [comment]
Hi!

Yes, it is actually superfluous to give that with the 'continue' it does
not reach i + 1.

I saw that you are  interested in the project, I don't know your
programming skills (not that mine are excellent), but if you like I can add
you as a contributor

Il giorno mar 23 mar 2021 alle ore 13:17 kir-malishev <
***@***.***> ha scritto:

**Comment by ferru97** [comment]
Solved

**Comment by kir-malishev** [comment]
Hi!

Now I am working on a small project under the direction of my supervisor, in which I need to programmatically search and process many scientific articles. Your library helped me a lot with this. I cannot promise to actively participate in the development of PyPaperBot, but I will try to contribute some.
