### ISSUE TITLE
Bibtex file encoding

### ISSUE THREAD

**Issue by kir-malishev** [ferru97/PyPaperBot#26]
Hi!

Is there any reason the .bib file is saved in latin-1 encoding? 

https://github.com/ferru97/PyPaperBot/blob/ee5b5020cb39396835ae7805483c3516169f3268/PyPaperBot/Paper.py#L96

Why not utf-8? Because of this, I have to change the encoding of the file before opening it.

**Comment by ferru97** [comment]
Hi!

Yes, I had some problem with the encoding of some foreign-accented names using utf-8, using latin-1 looked better.
If it is a problem we can try to add an argument at command line such as --bib_encoding to specify the preferred one
