### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by chuse4096** [ferru97/PyPaperBot#3]
Hello, I've been attempting to download books via the --doi command, but after inputting the relevant information for the DOI number and correct download dir, I get a 

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/XYZ/Downloads`/result.csv'

Any help would be appreciated, thanks

**Comment by ferru97** [comment]
Hi 
First of all thanks for your interest :)
Can you give me the exatc command that you input?

**Comment by chuse4096** [comment]
python -m PyPaperBot --doi="XYZ" --dwn-dir="C:\Users\XYZ\Downloads"`

also tried replacing 'python' with 'py' as per your suggestion

**Comment by ferru97** [comment]
Pay attention to the characters you use in the path, I think the problem is that **`** extra present in the two examples you gave me.
Try also with another directory

**Comment by ferru97** [comment]
@chuse4096 did you manage to solve?
